/**
 * The 99 Names of Allah, in the order of the narration in at-Tirmidhi (scholars differ over exactly
 * which names that list includes; the hadith that Allah has ninety-nine names is in Bukhari and Muslim).
 *
 * `ref` is an ayah where the name itself appears (`refKind: "name"`) or where Allah is described with its
 * meaning (`refKind: "meaning"`); root letters and quoted English were checked against the cited ayah.
 * `dua` is simple wording to make your own, unless `duaSource` names the Qur'an or Sunnah text it quotes.
 */

export interface NameOfAllah {
  number: number;
  arabic: string;
  transliteration: string;
  meaning: string;
  ref: string;
  refKind: "name" | "meaning";
  dua: string;
  duaSource?: string;
  live: string;
}

export const NAMES_OF_ALLAH: NameOfAllah[] = [
  {
    number: 1,
    arabic: "الرَّحْمَٰنُ",
    transliteration: "Ar-Rahman",
    meaning: "The Entirely Merciful",
    ref: "59:22",
    refKind: "name",
    dua: "Ya Rahman, let Your mercy reach every part of my life, and let it reach the people I love.",
    live: "Every mercy you receive begins with Him. Be gentle today with someone who is struggling.",
  },
  {
    number: 2,
    arabic: "الرَّحِيمُ",
    transliteration: "Ar-Raheem",
    meaning: "The Especially Merciful",
    ref: "59:22",
    refKind: "name",
    dua: "Ya Raheem, surround me with the special mercy You keep for those who believe.",
    live: "Return mercy with mercy: forgive a small wrong today without making the other person earn it.",
  },
  {
    number: 3,
    arabic: "الْمَلِكُ",
    transliteration: "Al-Malik",
    meaning: "The King",
    ref: "59:23",
    refKind: "name",
    dua: "Ya Malik, every matter I worry about is in Your kingdom. Take charge of my affairs and make me content with Your decree.",
    live: "When you feel powerless, remember whose kingdom it is, and serve Him well in the small part of it entrusted to you.",
  },
  {
    number: 4,
    arabic: "الْقُدُّوسُ",
    transliteration: "Al-Quddoos",
    meaning: "The Most Pure",
    ref: "59:23",
    refKind: "name",
    dua: "Ya Quddoos, purify my heart from envy, pride and everything that keeps me from You.",
    live: "Purify one thing today: your speech, your earnings, or your intention in something you already do.",
  },
  {
    number: 5,
    arabic: "السَّلَامُ",
    transliteration: "As-Salam",
    meaning: "The Source of Peace",
    ref: "59:23",
    refKind: "name",
    dua: "Ya Salam, grant me peace in my heart, my home and my faith, and make me a source of peace for others.",
    live: "Greet people with salam generously today, and be the calm voice in a tense conversation.",
  },
  {
    number: 6,
    arabic: "الْمُؤْمِنُ",
    transliteration: "Al-Mu'min",
    meaning: "The Giver of Faith and Security",
    ref: "59:23",
    refKind: "name",
    dua: "Ya Mu'min, give me security from what I fear and strengthen the faith You placed in my heart.",
    live: "Be someone others feel safe with: keep your word and protect the trust people place in you.",
  },
  {
    number: 7,
    arabic: "الْمُهَيْمِنُ",
    transliteration: "Al-Muhaymin",
    meaning: "The Ever-Watchful Guardian",
    ref: "59:23",
    refKind: "name",
    dua: "Ya Muhaymin, watch over me and my family in what I can see and what I cannot.",
    live: "Act today as someone who knows they are always seen, in private as in public.",
  },
  {
    number: 8,
    arabic: "الْعَزِيزُ",
    transliteration: "Al-'Azeez",
    meaning: "The Almighty",
    ref: "59:23",
    refKind: "name",
    dua: "Ya 'Azeez, give me dignity through obedience to You, never through what displeases You.",
    live: "Seek honour in doing what is right rather than in people's approval.",
  },
  {
    number: 9,
    arabic: "الْجَبَّارُ",
    transliteration: "Al-Jabbar",
    meaning: "The Compeller, the Restorer",
    ref: "59:23",
    refKind: "name",
    dua: "Ya Jabbar, mend what is broken in me and in my life, and restore what I have lost.",
    live: "He mends broken hearts. Be part of that today by checking on someone who is going through a hard time.",
  },
  {
    number: 10,
    arabic: "الْمُتَكَبِّرُ",
    transliteration: "Al-Mutakabbir",
    meaning: "The Supremely Great",
    ref: "59:23",
    refKind: "name",
    dua: "Ya Mutakabbir, all greatness is Yours. Remove every trace of arrogance from my heart.",
    live: "Greatness belongs to Allah alone. Practise humility today: admit a mistake or accept correction without defending yourself.",
  },
  {
    number: 11,
    arabic: "الْخَالِقُ",
    transliteration: "Al-Khaliq",
    meaning: "The Creator",
    ref: "59:24",
    refKind: "name",
    dua: "Ya Khaliq, You created me. Guide me to what I was created for.",
    live: "Really look at something He created today, the sky, a tree or your own hand, and say subhan Allah.",
  },
  {
    number: 12,
    arabic: "الْبَارِئُ",
    transliteration: "Al-Bari'",
    meaning: "The Maker",
    ref: "59:24",
    refKind: "name",
    dua: "Ya Bari', You brought me into being from nothing. Bring me out of every difficulty I am in.",
    live: "You were made with intention. Treat your body and your time as trusts from the One who made them.",
  },
  {
    number: 13,
    arabic: "الْمُصَوِّرُ",
    transliteration: "Al-Musawwir",
    meaning: "The Fashioner",
    ref: "59:24",
    refKind: "name",
    dua: "Ya Musawwir, You shaped me in the best form. Beautify my character as You beautified my form.",
    live: "Stop criticising how Allah made you or others. Thank Him for your form and work on your character instead.",
  },
  {
    number: 14,
    arabic: "الْغَفَّارُ",
    transliteration: "Al-Ghaffar",
    meaning: "The Ever-Forgiving",
    ref: "71:10",
    refKind: "name",
    dua: "Ya Ghaffar, forgive my sins again and again, the ones I remember and the ones I have forgotten.",
    live: "Say astaghfirullah often today, after every prayer and whenever you remember a mistake.",
  },
  {
    number: 15,
    arabic: "الْقَهَّارُ",
    transliteration: "Al-Qahhar",
    meaning: "The Subduer",
    ref: "13:16",
    refKind: "name",
    dua: "Ya Qahhar, subdue the desires that pull me away from You, and free me from fearing anything besides You.",
    live: "Nothing prevails over Allah. Face a fear today by doing the right thing anyway.",
  },
  {
    number: 16,
    arabic: "الْوَهَّابُ",
    transliteration: "Al-Wahhab",
    meaning: "The Bestower",
    ref: "3:8",
    refKind: "name",
    dua: "Our Lord, \"let not our hearts deviate after You have guided us and grant us from Yourself mercy. Indeed, You are the Bestower.\"",
    duaSource: "Qur'an 3:8",
    live: "Give something freely today without expecting anything back: a gift, your time, or a kind word.",
  },
  {
    number: 17,
    arabic: "الرَّزَّاقُ",
    transliteration: "Ar-Razzaq",
    meaning: "The Provider",
    ref: "51:58",
    refKind: "name",
    dua: "Ya Razzaq, provide for me what is lawful and good, and make me content with what You give.",
    live: "Seek your provision lawfully and without anxiety, and share some of what you have been given today.",
  },
  {
    number: 18,
    arabic: "الْفَتَّاحُ",
    transliteration: "Al-Fattah",
    meaning: "The Opener, the Judge",
    ref: "34:26",
    refKind: "name",
    dua: "Ya Fattah, open for me the doors of Your mercy, and open what is good that has been closed to me.",
    live: "When a door closes, keep asking and keep working. Open a door for someone else today.",
  },
  {
    number: 19,
    arabic: "الْعَلِيمُ",
    transliteration: "Al-'Aleem",
    meaning: "The All-Knowing",
    ref: "2:32",
    refKind: "name",
    dua: "Ya 'Aleem, You know what I need better than I do. Teach me what benefits me and let me benefit from what I learn.",
    live: "Learn one new thing about your deen today, and act on it.",
  },
  {
    number: 20,
    arabic: "الْقَابِضُ",
    transliteration: "Al-Qabid",
    meaning: "The Withholder",
    ref: "2:245",
    refKind: "meaning",
    dua: "Ya Qabid, Ya Basit, when You tighten my provision give me patience, and when You expand it give me gratitude.",
    live: "Hard seasons and easy seasons both come from Him. Meet tightness with patience and ease with generosity.",
  },
  {
    number: 21,
    arabic: "الْبَاسِطُ",
    transliteration: "Al-Basit",
    meaning: "The Extender",
    ref: "2:245",
    refKind: "meaning",
    dua: "Ya Basit, expand my chest, my provision and my time, and put blessing in them.",
    live: "When Allah expands something for you, extend it to others. Spend from what you have today.",
  },
  {
    number: 22,
    arabic: "الْخَافِضُ",
    transliteration: "Al-Khafid",
    meaning: "The One Who Lowers",
    ref: "56:3",
    refKind: "meaning",
    dua: "Ya Khafid, Ya Rafi', lower every trace of pride in me and raise me in Your sight.",
    live: "Only Allah truly lowers and raises. Don't look down on anyone, and don't be crushed when others look down on you.",
  },
  {
    number: 23,
    arabic: "الرَّافِعُ",
    transliteration: "Ar-Rafi'",
    meaning: "The One Who Raises",
    ref: "6:83",
    refKind: "meaning",
    dua: "Ya Rafi', raise my rank with You through faith, knowledge and good deeds.",
    live: "Invest today in what raises you with Allah: even ten minutes of learning or worship.",
  },
  {
    number: 24,
    arabic: "الْمُعِزُّ",
    transliteration: "Al-Mu'izz",
    meaning: "The Giver of Honour",
    ref: "3:26",
    refKind: "meaning",
    dua: "Ya Mu'izz, honour me with obedience to You, and do not disgrace me on the Day I meet You.",
    live: "Honour is from Allah alone. Protect someone's dignity today, and never humiliate anyone, even in a joke.",
  },
  {
    number: 25,
    arabic: "الْمُذِلُّ",
    transliteration: "Al-Mudhill",
    meaning: "The One Who Humbles",
    ref: "3:26",
    refKind: "meaning",
    dua: "Ya Mu'izz, Ya Mudhill, honour me through Your obedience and never humble me through my sins.",
    live: "Humble yourself before Allah willingly. Let go of the need to win every argument today.",
  },
  {
    number: 26,
    arabic: "السَّمِيعُ",
    transliteration: "As-Samee'",
    meaning: "The All-Hearing",
    ref: "42:11",
    refKind: "name",
    dua: "Ya Samee', You hear every whispered dua. Hear mine and answer it.",
    live: "He hears everything, so guard your tongue today and say only what you would be glad for Him to hear.",
  },
  {
    number: 27,
    arabic: "الْبَصِيرُ",
    transliteration: "Al-Baseer",
    meaning: "The All-Seeing",
    ref: "42:11",
    refKind: "name",
    dua: "Ya Baseer, You see what I go through when no one else does. Let me see the truth as truth.",
    live: "Do one good deed today that only Allah will see.",
  },
  {
    number: 28,
    arabic: "الْحَكَمُ",
    transliteration: "Al-Hakam",
    meaning: "The Judge",
    ref: "6:114",
    refKind: "name",
    dua: "Ya Hakam, judge with Your justice between me and those who have wronged me, and make me just when I judge.",
    live: "Before judging someone today, hear their side of the story.",
  },
  {
    number: 29,
    arabic: "الْعَدْلُ",
    transliteration: "Al-'Adl",
    meaning: "The Just",
    ref: "6:115",
    refKind: "meaning",
    dua: "Ya 'Adl, make me just with others and with myself, even when it goes against my own interest.",
    live: "Be fair in one situation today where it would be easy not to be: at home, at work, or in how you speak about someone.",
  },
  {
    number: 30,
    arabic: "اللَّطِيفُ",
    transliteration: "Al-Lateef",
    meaning: "The Subtle, the Kind",
    ref: "67:14",
    refKind: "name",
    dua: "Ya Lateef, be gentle with me in what You have decreed, and show me the kindness hidden in my difficulties.",
    live: "His kindness often works in ways you don't notice. Look back and find one hardship that turned out to carry good.",
  },
  {
    number: 31,
    arabic: "الْخَبِيرُ",
    transliteration: "Al-Khabeer",
    meaning: "The All-Aware",
    ref: "67:14",
    refKind: "name",
    dua: "Ya Khabeer, You know what is really going on inside me. Set right what I cannot even put into words.",
    live: "When you can't explain how you feel to anyone, bring it to Allah. He is already aware.",
  },
  {
    number: 32,
    arabic: "الْحَلِيمُ",
    transliteration: "Al-Haleem",
    meaning: "The Forbearing",
    ref: "2:225",
    refKind: "name",
    dua: "Ya Haleem, You do not take me to account for everything I do. Don't let me take Your forbearance for granted, and forgive me.",
    live: "Be forbearing today: don't react to the first provocation. Pause before you answer.",
  },
  {
    number: 33,
    arabic: "الْعَظِيمُ",
    transliteration: "Al-'Azeem",
    meaning: "The Magnificent",
    ref: "2:255",
    refKind: "name",
    dua: "Ya 'Azeem, fill my heart with Your greatness so that nothing else seems too big to face.",
    live: "Say subhana Rabbiyal-'Azeem slowly in your ruku' today, and feel what it means.",
  },
  {
    number: 34,
    arabic: "الْغَفُورُ",
    transliteration: "Al-Ghafoor",
    meaning: "The Forgiving",
    ref: "39:53",
    refKind: "name",
    dua: "Ya Ghafoor, forgive me completely, cover my faults and do not expose me.",
    live: "Never despair of His mercy: \"Indeed, Allah forgives all sins.\" Forgive someone today as you hope to be forgiven.",
  },
  {
    number: 35,
    arabic: "الشَّكُورُ",
    transliteration: "Ash-Shakoor",
    meaning: "The Appreciative",
    ref: "35:30",
    refKind: "name",
    dua: "Ya Shakoor, accept my small deeds and multiply them, and make me grateful for what You give.",
    live: "Allah rewards small deeds generously. Thank someone sincerely today, and don't dismiss any good deed as too small.",
  },
  {
    number: 36,
    arabic: "الْعَلِيُّ",
    transliteration: "Al-'Aliyy",
    meaning: "The Most High",
    ref: "2:255",
    refKind: "name",
    dua: "Ya 'Aliyy, raise my aspirations to what pleases You, and keep me humble before You.",
    live: "Say subhana Rabbiyal-A'la slowly in your sujood today: the lowest position, before the Most High.",
  },
  {
    number: 37,
    arabic: "الْكَبِيرُ",
    transliteration: "Al-Kabeer",
    meaning: "The Great",
    ref: "13:9",
    refKind: "name",
    dua: "Ya Kabeer, You are greater than every problem I have. Make my worries small in the light of Your greatness.",
    live: "Each time you say Allahu Akbar today, remind yourself: He is greater than what is worrying you.",
  },
  {
    number: 38,
    arabic: "الْحَفِيظُ",
    transliteration: "Al-Hafeez",
    meaning: "The Preserver",
    ref: "11:57",
    refKind: "name",
    dua: "Ya Hafeez, protect me, my faith and my family from every harm, seen and unseen.",
    live: "Guard what has been entrusted to you: your prayers, your promises, and other people's secrets.",
  },
  {
    number: 39,
    arabic: "الْمُقِيتُ",
    transliteration: "Al-Muqeet",
    meaning: "The Sustainer",
    ref: "4:85",
    refKind: "name",
    dua: "Ya Muqeet, nourish my body with what is good and my heart with Your remembrance.",
    live: "Eat with gratitude today: say bismillah, eat what is good, and share a meal if you can.",
  },
  {
    number: 40,
    arabic: "الْحَسِيبُ",
    transliteration: "Al-Haseeb",
    meaning: "The Reckoner, the Sufficient",
    ref: "4:6",
    refKind: "name",
    dua: "Hasbiyallah, Allah is sufficient for me. Ya Haseeb, be enough for me in everything that worries me.",
    live: "Take account of yourself before you are taken to account: spend five minutes tonight reviewing your day.",
  },
  {
    number: 41,
    arabic: "الْجَلِيلُ",
    transliteration: "Al-Jaleel",
    meaning: "The Majestic",
    ref: "55:27",
    refKind: "meaning",
    dua: "Ya Jaleel, fill my heart with an awe of You that keeps me from what You dislike.",
    live: "Let awe of Allah shape one decision today, especially one no one else will know about.",
  },
  {
    number: 42,
    arabic: "الْكَرِيمُ",
    transliteration: "Al-Kareem",
    meaning: "The Generous",
    ref: "82:6",
    refKind: "name",
    dua: "Ya Kareem, treat me with Your generosity, not with what I deserve.",
    live: "Be generous beyond what is expected: with money, with time, or by overlooking someone's mistake.",
  },
  {
    number: 43,
    arabic: "الرَّقِيبُ",
    transliteration: "Ar-Raqeeb",
    meaning: "The Watchful",
    ref: "4:1",
    refKind: "name",
    dua: "Ya Raqeeb, make me mindful that You are watching, so that I feel shy to disobey You.",
    live: "Before you open something you shouldn't, remember that He is watching.",
  },
  {
    number: 44,
    arabic: "الْمُجِيبُ",
    transliteration: "Al-Mujeeb",
    meaning: "The Responsive",
    ref: "11:61",
    refKind: "name",
    dua: "Ya Mujeeb, I am calling on You. Answer my dua in the way that is best for me.",
    live: "He is \"near and responsive.\" Keep asking, and answer His call to prayer promptly today.",
  },
  {
    number: 45,
    arabic: "الْوَاسِعُ",
    transliteration: "Al-Wasi'",
    meaning: "The All-Encompassing",
    ref: "2:115",
    refKind: "name",
    dua: "Ya Wasi', let Your mercy and forgiveness encompass me, and widen my heart for people.",
    live: "Make room in your heart for people who are different from you, and think well of them.",
  },
  {
    number: 46,
    arabic: "الْحَكِيمُ",
    transliteration: "Al-Hakeem",
    meaning: "The Wise",
    ref: "2:32",
    refKind: "name",
    dua: "Ya Hakeem, make me content with Your wisdom in what I don't understand, and give me wisdom in my choices.",
    live: "When something doesn't make sense to you, remind yourself that your Lord is Wise.",
  },
  {
    number: 47,
    arabic: "الْوَدُودُ",
    transliteration: "Al-Wadood",
    meaning: "The Loving",
    ref: "85:14",
    refKind: "name",
    dua: "Ya Wadood, make me beloved to You, and put love between me and the people around me.",
    live: "Show love through action today: a message, a visit, or a kindness to your family.",
  },
  {
    number: 48,
    arabic: "الْمَجِيدُ",
    transliteration: "Al-Majeed",
    meaning: "The Glorious",
    ref: "11:73",
    refKind: "name",
    dua: "Ya Majeed, You are worthy of all glory. Let my life glorify You.",
    live: "Send blessings on the Prophet ﷺ today. The prayer upon him ends with innaka Hameedun Majeed.",
  },
  {
    number: 49,
    arabic: "الْبَاعِثُ",
    transliteration: "Al-Ba'ith",
    meaning: "The Resurrector",
    ref: "22:7",
    refKind: "meaning",
    dua: "Ya Ba'ith, raise me on the Day of Resurrection among those You are pleased with.",
    live: "Live today as someone who will be raised again. What would you want to have done?",
  },
  {
    number: 50,
    arabic: "الشَّهِيدُ",
    transliteration: "Ash-Shaheed",
    meaning: "The Witness",
    ref: "4:79",
    refKind: "name",
    dua: "Ya Shaheed, You witness everything. Be witness to my good deeds and forgive what You have seen of my sins.",
    live: "Be truthful today, even in small things: don't exaggerate and don't hide the truth.",
  },
  {
    number: 51,
    arabic: "الْحَقُّ",
    transliteration: "Al-Haqq",
    meaning: "The Truth",
    ref: "22:6",
    refKind: "name",
    dua: "Ya Haqq, show me the truth as truth and help me follow it, and falsehood as falsehood and help me avoid it.",
    live: "Stand for the truth today even when it is uncomfortable: gently, but clearly.",
  },
  {
    number: 52,
    arabic: "الْوَكِيلُ",
    transliteration: "Al-Wakeel",
    meaning: "The Trustee",
    ref: "3:173",
    refKind: "name",
    dua: "Hasbunallahu wa ni'mal-wakeel: \"Sufficient for us is Allah, and He is the best Disposer of affairs.\"",
    duaSource: "Qur'an 3:173",
    live: "Do your part, then truly let it go. Name one worry today and entrust it to Allah.",
  },
  {
    number: 53,
    arabic: "الْقَوِيُّ",
    transliteration: "Al-Qawiyy",
    meaning: "The Strong",
    ref: "22:40",
    refKind: "name",
    dua: "Ya Qawiyy, strengthen me where I am weak, in body and in faith.",
    live: "Use your strength for others: help carry someone's load today, literally or otherwise.",
  },
  {
    number: 54,
    arabic: "الْمَتِينُ",
    transliteration: "Al-Mateen",
    meaning: "The Firm",
    ref: "51:58",
    refKind: "name",
    dua: "Ya Mateen, make me firm on Your religion and steady when things get hard.",
    live: "Build one small, steady habit, like two rak'ahs or a page of Qur'an, and keep it daily.",
  },
  {
    number: 55,
    arabic: "الْوَلِيُّ",
    transliteration: "Al-Waliyy",
    meaning: "The Protecting Ally",
    ref: "2:257",
    refKind: "name",
    dua: "Ya Waliyy, be my protector and ally in this world and the next.",
    live: "Take Allah as your ally: seek His pleasure over people's, and stand by the believers.",
  },
  {
    number: 56,
    arabic: "الْحَمِيدُ",
    transliteration: "Al-Hameed",
    meaning: "The Praiseworthy",
    ref: "35:15",
    refKind: "name",
    dua: "Ya Hameed, all praise is Yours. Make me among those who praise You in ease and in hardship.",
    live: "Say alhamdulillah today for three specific things, including something difficult.",
  },
  {
    number: 57,
    arabic: "الْمُحْصِي",
    transliteration: "Al-Muhsi",
    meaning: "The One Who Counts All Things",
    ref: "72:28",
    refKind: "meaning",
    dua: "Ya Muhsi, You have counted every breath and every deed. Count my good deeds and forgive my sins.",
    live: "Nothing is too small to be counted. Do a small good deed today and don't belittle it.",
  },
  {
    number: 58,
    arabic: "الْمُبْدِئُ",
    transliteration: "Al-Mubdi'",
    meaning: "The Originator",
    ref: "85:13",
    refKind: "meaning",
    dua: "Ya Mubdi', You began my life. Give me a new beginning with You today.",
    live: "Start something good today: a new habit, or a fresh start with someone.",
  },
  {
    number: 59,
    arabic: "الْمُعِيدُ",
    transliteration: "Al-Mu'eed",
    meaning: "The Restorer",
    ref: "85:13",
    refKind: "meaning",
    dua: "Ya Mubdi', Ya Mu'eed, You began creation and will bring it back. Bring me back to You whenever I drift.",
    live: "When you slip, return. Every return to Allah is welcome.",
  },
  {
    number: 60,
    arabic: "الْمُحْيِي",
    transliteration: "Al-Muhyi",
    meaning: "The Giver of Life",
    ref: "57:2",
    refKind: "meaning",
    dua: "Ya Muhyi, bring my heart back to life with faith, as You bring the earth to life after its death.",
    live: "Revive something that has died in you: a sunnah you used to keep, or a relationship you let go.",
  },
  {
    number: 61,
    arabic: "الْمُمِيتُ",
    transliteration: "Al-Mumeet",
    meaning: "The Bringer of Death",
    ref: "57:2",
    refKind: "meaning",
    dua: "O Allah, keep me alive as long as life is better for me, and take me when death is better for me.",
    duaSource: "Taught by the Prophet ﷺ (Bukhari and Muslim)",
    live: "Remember death without fear, as a reason to make today count.",
  },
  {
    number: 62,
    arabic: "الْحَيُّ",
    transliteration: "Al-Hayy",
    meaning: "The Ever-Living",
    ref: "2:255",
    refKind: "name",
    dua: "Ya Hayyu Ya Qayyum, bi rahmatika astagheeth: O Ever-Living, O Sustainer of all, by Your mercy I seek relief.",
    duaSource: "Taught by the Prophet ﷺ (at-Tirmidhi)",
    live: "Everyone you rely on will die; He never will. Rely on the Ever-Living today.",
  },
  {
    number: 63,
    arabic: "الْقَيُّومُ",
    transliteration: "Al-Qayyoom",
    meaning: "The Sustainer of All",
    ref: "2:255",
    refKind: "name",
    dua: "Ya Qayyoom, You hold everything together. Hold my life together and do not leave me to myself.",
    live: "Read Ayat al-Kursi today and reflect on the two names in it: Al-Hayy and Al-Qayyoom.",
  },
  {
    number: 64,
    arabic: "الْوَاجِدُ",
    transliteration: "Al-Wajid",
    meaning: "The Finder, Who Lacks Nothing",
    ref: "93:7",
    refKind: "meaning",
    dua: "Ya Wajid, You lack nothing and find everything. Let me find You whenever I am lost.",
    live: "He \"found you lost and guided\" you. Help someone find their way today.",
  },
  {
    number: 65,
    arabic: "الْمَاجِدُ",
    transliteration: "Al-Majid",
    meaning: "The Noble",
    ref: "85:15",
    refKind: "meaning",
    dua: "Ya Majid, give to me from Your noble generosity, and make me noble in character.",
    live: "Carry yourself with nobility today: generous, dignified, and above petty arguments.",
  },
  {
    number: 66,
    arabic: "الْوَاحِدُ",
    transliteration: "Al-Wahid",
    meaning: "The One",
    ref: "13:16",
    refKind: "name",
    dua: "Ya Wahid, let my heart turn to You alone, free of every false dependence.",
    live: "Check your intentions today: is this for Him alone? Sincerity is living His oneness.",
  },
  {
    number: 67,
    arabic: "الْأَحَدُ",
    transliteration: "Al-Ahad",
    meaning: "The Unique One",
    ref: "112:1",
    refKind: "name",
    dua: "Ya Ahad, Ya Samad, keep my belief in Your oneness pure until I meet You.",
    live: "Recite Surah al-Ikhlas today and reflect on it: it describes Him as Al-Ahad and As-Samad.",
  },
  {
    number: 68,
    arabic: "الصَّمَدُ",
    transliteration: "As-Samad",
    meaning: "The Eternal Refuge",
    ref: "112:2",
    refKind: "name",
    dua: "Ya Samad, You are the One everyone turns to in need. I turn to You with all of mine.",
    live: "Before asking anyone else for help today, ask Allah first.",
  },
  {
    number: 69,
    arabic: "الْقَادِرُ",
    transliteration: "Al-Qadir",
    meaning: "The Able",
    ref: "6:65",
    refKind: "name",
    dua: "Ya Qadir, nothing is impossible for You. Make easy for me what seems impossible.",
    live: "Don't write off as impossible anything you can still ask for. Make a bold dua today.",
  },
  {
    number: 70,
    arabic: "الْمُقْتَدِرُ",
    transliteration: "Al-Muqtadir",
    meaning: "The All-Powerful",
    ref: "54:42",
    refKind: "name",
    dua: "Ya Muqtadir, Your power is complete. Enable me to do what pleases You.",
    live: "When you have power over someone, a child or an employee, use it gently, knowing His power is over you.",
  },
  {
    number: 71,
    arabic: "الْمُقَدِّمُ",
    transliteration: "Al-Muqaddim",
    meaning: "The One Who Brings Forward",
    ref: "50:28",
    refKind: "meaning",
    dua: "Ya Muqaddim, Ya Mu'akhkhir, bring forward for me what is good and hold back from me what is harmful.",
    live: "Hurry to good deeds today, and don't postpone repentance.",
  },
  {
    number: 72,
    arabic: "الْمُؤَخِّرُ",
    transliteration: "Al-Mu'akhkhir",
    meaning: "The One Who Delays",
    ref: "71:4",
    refKind: "meaning",
    dua: "O Allah, don't let me delay my return to You, and don't let me rush what You have delayed for me.",
    live: "Be patient with a delay today: something you wanted that hasn't come yet. His timing is wise.",
  },
  {
    number: 73,
    arabic: "الْأَوَّلُ",
    transliteration: "Al-Awwal",
    meaning: "The First",
    ref: "57:3",
    refKind: "name",
    dua: "Ya Awwal, You were before everything. Be first in my heart and first in my day.",
    live: "Begin your day with Him: pray Fajr on time and remember Him before you reach for your phone.",
  },
  {
    number: 74,
    arabic: "الْآخِرُ",
    transliteration: "Al-Akhir",
    meaning: "The Last",
    ref: "57:3",
    refKind: "name",
    dua: "Ya Akhir, You remain after everything. Make la ilaha illallah the last of my words.",
    live: "End your day with Him: a short remembrance before you sleep.",
  },
  {
    number: 75,
    arabic: "الظَّاهِرُ",
    transliteration: "Az-Zahir",
    meaning: "The Manifest",
    ref: "57:3",
    refKind: "name",
    dua: "Ya Zahir, let Your signs be clear to me in everything I see.",
    live: "Look for His signs in the ordinary today: rain, a meal, a smile.",
  },
  {
    number: 76,
    arabic: "الْبَاطِنُ",
    transliteration: "Al-Batin",
    meaning: "The Hidden, the Near",
    ref: "57:3",
    refKind: "name",
    dua: "Ya Batin, You know my inner self. Purify what is hidden in me.",
    live: "Work on something hidden today: a private good deed, or letting go of a grudge no one knows about.",
  },
  {
    number: 77,
    arabic: "الْوَالِي",
    transliteration: "Al-Wali",
    meaning: "The Governor",
    ref: "13:11",
    refKind: "meaning",
    dua: "Ya Wali, take charge of my affairs and manage them for me with Your wisdom.",
    live: "If you are responsible for others, look after them with justice and care today.",
  },
  {
    number: 78,
    arabic: "الْمُتَعَالِي",
    transliteration: "Al-Muta'ali",
    meaning: "The Most Exalted",
    ref: "13:9",
    refKind: "name",
    dua: "Ya Muta'ali, lift my heart above petty things toward what pleases You.",
    live: "Rise above a grudge or a pointless argument today.",
  },
  {
    number: 79,
    arabic: "الْبَرُّ",
    transliteration: "Al-Barr",
    meaning: "The Source of Goodness",
    ref: "52:28",
    refKind: "name",
    dua: "Ya Barr, be good to me and my parents, and make me dutiful to them.",
    live: "Be good to your parents today in a concrete way: a call, a visit, or a dua for them.",
  },
  {
    number: 80,
    arabic: "التَّوَّابُ",
    transliteration: "At-Tawwab",
    meaning: "The Accepter of Repentance",
    ref: "2:37",
    refKind: "name",
    dua: "Ya Tawwab, turn to me so that I turn to You, and accept my repentance.",
    live: "Repent today for one specific thing, and resolve not to return to it.",
  },
  {
    number: 81,
    arabic: "الْمُنْتَقِمُ",
    transliteration: "Al-Muntaqim",
    meaning: "The One Who Exacts Retribution",
    ref: "32:22",
    refKind: "meaning",
    dua: "O Allah, protect me from wronging anyone, and from being among those who deserve Your retribution.",
    live: "Leave revenge to Allah. Seek justice properly, or forgive.",
  },
  {
    number: 82,
    arabic: "الْعَفُوُّ",
    transliteration: "Al-'Afuww",
    meaning: "The Pardoner",
    ref: "4:99",
    refKind: "name",
    dua: "Allahumma innaka 'afuwwun tuhibbul-'afwa fa'fu 'anni: O Allah, You are Pardoning and love to pardon, so pardon me.",
    duaSource: "Taught by the Prophet ﷺ (at-Tirmidhi)",
    live: "Pardon someone today: not only forgive, but wipe the matter away completely.",
  },
  {
    number: 83,
    arabic: "الرَّؤُوفُ",
    transliteration: "Ar-Ra'oof",
    meaning: "The Most Kind",
    ref: "2:143",
    refKind: "name",
    dua: "Ya Ra'oof, be most kind to me in my weakness.",
    live: "Be tender with the vulnerable today: the elderly, children, and animals.",
  },
  {
    number: 84,
    arabic: "مَالِكُ الْمُلْكِ",
    transliteration: "Malik al-Mulk",
    meaning: "Owner of Sovereignty",
    ref: "3:26",
    refKind: "name",
    dua: "\"O Allah, Owner of Sovereignty\", give me what is good in this world and the next, and let nothing I own own me.",
    live: "Hold what you own lightly. Give something away today to remind yourself who the true Owner is.",
  },
  {
    number: 85,
    arabic: "ذُو الْجَلَالِ وَالْإِكْرَامِ",
    transliteration: "Dhul-Jalali wal-Ikram",
    meaning: "Possessor of Majesty and Honour",
    ref: "55:78",
    refKind: "name",
    dua: "Ya Dhal-Jalali wal-Ikram, fill my heart with Your majesty and honour me with Your generosity.",
    duaSource: "Calling on this name is encouraged by the Prophet ﷺ (at-Tirmidhi)",
    live: "The Prophet ﷺ urged us to call on Allah often by this name. Begin your duas with it today.",
  },
  {
    number: 86,
    arabic: "الْمُقْسِطُ",
    transliteration: "Al-Muqsit",
    meaning: "The Equitable",
    ref: "3:18",
    refKind: "meaning",
    dua: "Ya Muqsit, make me fair in all my dealings, and establish justice for the oppressed.",
    live: "Give full measure today: in your work, in trade, and in how you describe others.",
  },
  {
    number: 87,
    arabic: "الْجَامِعُ",
    transliteration: "Al-Jami'",
    meaning: "The Gatherer",
    ref: "3:9",
    refKind: "meaning",
    dua: "Ya Jami', gather my scattered heart, and gather me with those I love in Your pleasure and in Jannah.",
    live: "Bring people together today: reconcile two people, or reconnect with family.",
  },
  {
    number: 88,
    arabic: "الْغَنِيُّ",
    transliteration: "Al-Ghaniyy",
    meaning: "The Free of Need",
    ref: "35:15",
    refKind: "name",
    dua: "Ya Ghaniyy, You need nothing from me. Make me rich in heart and in need of You alone.",
    live: "True richness is contentment. Stop comparing what you have with others today.",
  },
  {
    number: 89,
    arabic: "الْمُغْنِي",
    transliteration: "Al-Mughni",
    meaning: "The Enricher",
    ref: "9:28",
    refKind: "meaning",
    dua: "Allahummak-fini bi halalika 'an haramik, wa aghnini bi fadlika 'amman siwak: O Allah, suffice me with what You have made lawful instead of what You have forbidden, and make me independent of all besides You by Your bounty.",
    duaSource: "Taught by the Prophet ﷺ (at-Tirmidhi)",
    live: "Help someone become independent today: teach a skill, or support someone's small business.",
  },
  {
    number: 90,
    arabic: "الْمَانِعُ",
    transliteration: "Al-Mani'",
    meaning: "The Withholder",
    ref: "35:2",
    refKind: "meaning",
    dua: "Allahumma la mani'a lima a'tayt, wa la mu'tiya lima mana't: O Allah, none can withhold what You give, and none can give what You withhold.",
    duaSource: "Taught by the Prophet ﷺ (Bukhari)",
    live: "When something is withheld from you, trust that it may be a protection.",
  },
  {
    number: 91,
    arabic: "الضَّارُّ",
    transliteration: "Ad-Darr",
    meaning: "The One Who Decrees Harm",
    ref: "48:11",
    refKind: "meaning",
    dua: "O Allah, no harm and no benefit comes except by Your will. Protect me from harm and bring me what benefits me.",
    live: "Don't fear people or things as if they could harm you on their own. Fear Allah alone, and take sensible precautions.",
  },
  {
    number: 92,
    arabic: "النَّافِعُ",
    transliteration: "An-Nafi'",
    meaning: "The One Who Brings Benefit",
    ref: "48:11",
    refKind: "meaning",
    dua: "Ya Nafi', let me benefit from what I learn, and make me of benefit to others.",
    live: "Be useful to someone today in a practical way.",
  },
  {
    number: 93,
    arabic: "النُّورُ",
    transliteration: "An-Noor",
    meaning: "The Light",
    ref: "24:35",
    refKind: "name",
    dua: "Allahumma ij'al fi qalbi nooran, wa fi basari nooran, wa fi sam'i nooran: O Allah, place light in my heart, light in my sight and light in my hearing.",
    duaSource: "Taught by the Prophet ﷺ (Bukhari and Muslim)",
    live: "Read the Verse of Light today and reflect on it.",
  },
  {
    number: 94,
    arabic: "الْهَادِي",
    transliteration: "Al-Hadi",
    meaning: "The Guide",
    ref: "22:54",
    refKind: "name",
    dua: "Ya Hadi, guide me to the straight path and keep me on it.",
    live: "Share one piece of guidance gently today, more by example than by words.",
  },
  {
    number: 95,
    arabic: "الْبَدِيعُ",
    transliteration: "Al-Badee'",
    meaning: "The Incomparable Originator",
    ref: "2:117",
    refKind: "name",
    dua: "Ya Badee', Originator of the heavens and the earth, bring about for me good I cannot imagine.",
    live: "Be creative in doing good: find a new way to help someone today.",
  },
  {
    number: 96,
    arabic: "الْبَاقِي",
    transliteration: "Al-Baqi",
    meaning: "The Everlasting",
    ref: "55:27",
    refKind: "meaning",
    dua: "Ya Baqi, make my deeds among those that last, and don't let my heart attach itself to what will fade.",
    live: "Invest in what remains: ongoing charity, knowledge that benefits others, or raising a righteous child.",
  },
  {
    number: 97,
    arabic: "الْوَارِثُ",
    transliteration: "Al-Warith",
    meaning: "The Inheritor",
    ref: "21:89",
    refKind: "name",
    dua: "Rabbi la tadharni fardan wa anta khayrul-waritheen: \"My Lord, do not leave me alone, while You are the best of inheritors.\"",
    duaSource: "Qur'an 21:89",
    live: "Everything you own will be inherited. Give some of it away now, while it is still yours to give.",
  },
  {
    number: 98,
    arabic: "الرَّشِيدُ",
    transliteration: "Ar-Rasheed",
    meaning: "The Guide to What Is Right",
    ref: "18:10",
    refKind: "meaning",
    dua: "Rabbana atina min ladunka rahmatan wa hayyi' lana min amrina rashada: \"Our Lord, grant us from Yourself mercy and prepare for us from our affair right guidance.\"",
    duaSource: "Qur'an 18:10",
    live: "Before a big decision, pray istikharah and seek the advice of someone wise.",
  },
  {
    number: 99,
    arabic: "الصَّبُورُ",
    transliteration: "As-Saboor",
    meaning: "The Patient",
    ref: "16:61",
    refKind: "meaning",
    dua: "Ya Saboor, give me patience, as You are patient with me.",
    live: "Allah does not hasten to punish our wrongs. Be patient with someone today, and slow to anger.",
  },
];

export function getNameOfAllah(number: number): NameOfAllah | undefined {
  return NAMES_OF_ALLAH.find((name) => name.number === number);
}

/** Same name for everyone on the same local calendar date, cycling through all 99. */
export function nameOfTheDay(date: Date): NameOfAllah {
  const dayNumber = Math.floor(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()) / 86_400_000);
  return NAMES_OF_ALLAH[dayNumber % NAMES_OF_ALLAH.length]!;
}
